# Generated by Django 3.0.3 on 2020-02-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='picture',
            name='date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата добавления'),
        ),
    ]
