# Generated by Django 3.0.3 on 2020-02-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20200222_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date',
            field=models.DateField(auto_now_add=True, default=None, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
    ]
