# Generated by Django 3.0.3 on 2020-02-22 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(default=None, max_length=20, verbose_name='Фамилия')),
                ('email', models.EmailField(default=None, max_length=30, unique=True, verbose_name='Имейл')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Пользователь', to=settings.AUTH_USER_MODEL, verbose_name='аккаунт')),
            ],
        ),
    ]
